// Real PostgreSQL engine in memory; synthetic organizations and billing only.
// No network, payment provider, patient data, or live Supabase writes are used.
import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

const db = new PGlite();
const migration = fs.readFileSync(new URL('../supabase/paid-access-gate.sql', import.meta.url), 'utf8');
const uploadTriggerFix = fs.readFileSync(
  new URL('../supabase/paid-upload-reservation-trigger-fix.sql', import.meta.url),
  'utf8',
);
const liveUser = '11111111-1111-4111-8111-111111111111';
const unpaidUser = '22222222-2222-4222-8222-222222222222';
const ordinarySandboxMember = '33333333-3333-4333-8333-333333333333';
const sandboxUser = '5ebb6f53-f8b6-464d-af65-c19fa3a28e85';
const liveOrg = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const unpaidOrg = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const sandboxOrg = 'cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const liveDocument = 'dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const unpaidDocument = 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
const sandboxDocument = 'ffffffff-ffff-4fff-8fff-ffffffffffff';
const livePrice = 'pri_01m2gcpjxz4wqjft7z10zcz3zq';
const sandboxPrice = 'pri_01m2xtx7y26neywx40s3v3s5k3';

before(async () => {
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role;
    create role authenticator;
    create schema auth;
    create schema careflow_private;
    create schema storage;
    create function auth.uid() returns uuid language sql stable as
      $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;

    create table auth.users (id uuid primary key);
    create table public.organizations (id uuid primary key, name text not null);
    create table public.organization_members (
      id uuid primary key default gen_random_uuid(),
      organization_id uuid not null references public.organizations(id),
      user_id uuid not null references auth.users(id),
      role text not null default 'staff'
    );
    create table public.organization_subscriptions (
      organization_id uuid primary key references public.organizations(id),
      provider text not null default 'paddle',
      provider_variant_id text not null,
      status text not null,
      test_mode boolean not null default false
    );
    create table public.documents (
      id uuid primary key default gen_random_uuid(),
      organization_id uuid not null references public.organizations(id),
      file_name text,
      storage_path text
    );
    create table public.cases (
      id bigint generated by default as identity primary key,
      document_id uuid references public.documents(id),
      organization_id uuid not null references public.organizations(id),
      file_name text,
      document_type text,
      status text not null default 'Review',
      patient_name text,
      document_date date,
      insurance_information text,
      missing_information text,
      review_notes text,
      review_revision bigint not null default 0,
      processing_status text not null default 'pending',
      processing_error_code text,
      processing_error_message text,
      processing_attempts integer not null default 0,
      processing_started_at timestamptz,
      processing_completed_at timestamptz,
      processing_run_id uuid,
      processing_requested_by uuid,
      processing_retryable boolean not null default true
    );
    create table careflow_private.document_upload_reservations (
      id uuid primary key,
      organization_id uuid not null references public.organizations(id),
      created_by uuid not null references auth.users(id),
      storage_path text not null unique,
      created_at timestamptz not null,
      expires_at timestamptz not null,
      uploaded_at timestamptz
    );
    create table careflow_private.document_processing_attempts (
      id bigint generated always as identity primary key,
      case_id bigint not null references public.cases(id),
      document_id uuid not null references public.documents(id),
      organization_id uuid not null references public.organizations(id),
      run_id uuid not null,
      attempt_number integer not null,
      requested_by uuid not null references auth.users(id),
      status text not null,
      started_at timestamptz not null,
      finished_at timestamptz
    );
    create table storage.objects (
      id uuid primary key default gen_random_uuid(),
      bucket_id text,
      name text,
      owner_id text
    );

    alter table public.organization_members enable row level security;
    alter table public.documents enable row level security;
    alter table public.cases enable row level security;
    grant usage on schema auth to authenticated;
    grant select on public.organization_members to authenticated;
    grant select, insert on public.documents to authenticated;
    grant select, insert, update on public.cases to authenticated;
    create policy member_self on public.organization_members for select to authenticated
      using (user_id = (select auth.uid()));
    create policy document_member_select on public.documents for select to authenticated
      using (exists(select 1 from public.organization_members om where om.user_id=(select auth.uid()) and om.organization_id=documents.organization_id));
    create policy document_member_insert on public.documents for insert to authenticated
      with check (exists(select 1 from public.organization_members om where om.user_id=(select auth.uid()) and om.organization_id=documents.organization_id));
    create policy case_member_select on public.cases for select to authenticated
      using (exists(select 1 from public.organization_members om where om.user_id=(select auth.uid()) and om.organization_id=cases.organization_id));
    create policy case_member_insert on public.cases for insert to authenticated
      with check (exists(select 1 from public.organization_members om where om.user_id=(select auth.uid()) and om.organization_id=cases.organization_id));
    create policy case_member_update on public.cases for update to authenticated
      using (exists(select 1 from public.organization_members om where om.user_id=(select auth.uid()) and om.organization_id=cases.organization_id))
      with check (exists(select 1 from public.organization_members om where om.user_id=(select auth.uid()) and om.organization_id=cases.organization_id));

    insert into auth.users values
      ('${liveUser}'), ('${unpaidUser}'), ('${ordinarySandboxMember}'), ('${sandboxUser}');
    insert into public.organizations values
      ('${liveOrg}', 'Synthetic Live Clinic'),
      ('${unpaidOrg}', 'Synthetic Read-only Clinic'),
      ('${sandboxOrg}', 'Synthetic Sandbox Clinic');
    insert into public.organization_members (organization_id,user_id,role) values
      ('${liveOrg}','${liveUser}','admin'),
      ('${unpaidOrg}','${unpaidUser}','admin'),
      ('${sandboxOrg}','${sandboxUser}','admin'),
      ('${sandboxOrg}','${ordinarySandboxMember}','staff');
    insert into public.organization_subscriptions values
      ('${liveOrg}','paddle','${livePrice}','active',false),
      ('${sandboxOrg}','paddle','${sandboxPrice}','active',true);
    insert into public.documents (id,organization_id,file_name,storage_path) values
      ('${liveDocument}','${liveOrg}','Synthetic Live.pdf','${liveOrg}/${liveDocument}.pdf'),
      ('${unpaidDocument}','${unpaidOrg}','Synthetic Existing.pdf','${unpaidOrg}/${unpaidDocument}.pdf'),
      ('${sandboxDocument}','${sandboxOrg}','Synthetic Sandbox.pdf','${sandboxOrg}/${sandboxDocument}.pdf');
    insert into public.cases (document_id,organization_id,file_name) values
      ('${liveDocument}','${liveOrg}','Synthetic Live.pdf'),
      ('${unpaidDocument}','${unpaidOrg}','Synthetic Existing.pdf'),
      ('${sandboxDocument}','${sandboxOrg}','Synthetic Sandbox.pdf');
  `);
  await db.exec(migration);
  await db.exec(uploadTriggerFix);
});

after(() => db.close());

async function asUser(userId, sql) {
  await db.exec(`set role authenticated; set request.jwt.claim.sub = '${userId}';`);
  try {
    return (await db.query(sql)).rows;
  } finally {
    await db.exec("reset role; set request.jwt.claim.sub = ''; ");
  }
}

async function asService(sql) {
  await db.exec("set role service_role; set request.jwt.claim.sub = ''; ");
  try {
    return (await db.query(sql)).rows;
  } finally {
    await db.exec('reset role;');
  }
}

test('live access and the isolated Sandbox identity are accepted without a general test bypass', async () => {
  assert.equal((await asUser(liveUser,
    `select public.careflow_has_paid_access('${liveOrg}') as allowed`))[0].allowed, true);
  assert.equal((await asUser(sandboxUser,
    `select public.careflow_has_paid_access('${sandboxOrg}') as allowed`))[0].allowed, true);
  assert.equal((await asUser(ordinarySandboxMember,
    `select public.careflow_has_paid_access('${sandboxOrg}') as allowed`))[0].allowed, false);
  assert.equal((await asUser(liveUser,
    `select public.careflow_has_paid_access('${sandboxOrg}') as allowed`))[0].allowed, false);
  await assert.rejects(
    asUser(liveUser,
      `select careflow_private.organization_has_paid_access('${sandboxOrg}','${sandboxUser}')`),
    /permission denied/i,
  );
});

test('unpaid members can read existing cases but cannot insert documents or change cases', async () => {
  const visible = await asUser(unpaidUser, `select id,status from public.cases where organization_id='${unpaidOrg}'`);
  assert.equal(visible.length, 1);
  const changed = await asUser(unpaidUser,
    `update public.cases set status='Completed' where organization_id='${unpaidOrg}' returning id`);
  assert.equal(changed.length, 0);
  await assert.rejects(
    asUser(unpaidUser,
      `insert into public.documents(organization_id,file_name,storage_path) values('${unpaidOrg}','Blocked.pdf','${unpaidOrg}/00000000-0000-4000-8000-000000000000.pdf')`),
    /row-level security policy/i,
  );
});

test('paid live members retain case updates and upload reservations', async () => {
  const changed = await asUser(liveUser,
    `update public.cases set status='Correction Required' where organization_id='${liveOrg}' returning id`);
  assert.equal(changed.length, 1);
  const [reservation] = await asUser(liveUser, 'select * from public.careflow_reserve_document_upload()');
  assert.match(reservation.storage_path, new RegExp(`^${liveOrg}/[0-9a-f-]{36}\\.pdf$`, 'i'));

  await db.exec(`update public.organization_subscriptions set status='paused' where organization_id='${liveOrg}'`);
  assert.equal((await asUser(liveUser,
    `select careflow_private.storage_upload_is_reserved('${reservation.storage_path}') as allowed`))[0].allowed, false);
  await assert.rejects(
    asUser(liveUser, 'select * from public.careflow_reserve_document_upload()'),
    /active CareFlow subscription/i,
  );
  await db.exec(`update public.organization_subscriptions set status='active' where organization_id='${liveOrg}'`);
});

test('Storage consumes a reservation using its JWT-derived object owner', async () => {
  const [reservation] = await asUser(liveUser, 'select * from public.careflow_reserve_document_upload()');

  // Supabase Storage can perform its internal metadata insert after the direct
  // auth.uid() context is gone. owner_id is the persisted JWT subject.
  await db.exec(`
    set request.jwt.claim.sub = '';
    insert into storage.objects(bucket_id,name,owner_id)
    values ('documents','${reservation.storage_path}','${liveUser}')
  `);

  const consumed = (await db.query(
    `select uploaded_at from careflow_private.document_upload_reservations where storage_path='${reservation.storage_path}'`,
  )).rows[0];
  assert.ok(consumed.uploaded_at);
});

test('Storage rejects an object owner who did not create the reservation', async () => {
  const [reservation] = await asUser(liveUser, 'select * from public.careflow_reserve_document_upload()');

  await assert.rejects(
    db.exec(`
      set request.jwt.claim.sub = '';
      insert into storage.objects(bucket_id,name,owner_id)
      values ('documents','${reservation.storage_path}','${unpaidUser}')
    `),
    /valid paid upload reservation/i,
  );

  const state = (await db.query(
    `select uploaded_at from careflow_private.document_upload_reservations where storage_path='${reservation.storage_path}'`,
  )).rows[0];
  assert.equal(state.uploaded_at, null);
});

test('AI and staff service boundaries return no paid capability for an unpaid hospital', async () => {
  const [claim] = await asService(
    `select * from public.careflow_claim_document_processing(
      2,'${unpaidDocument}','${unpaidOrg}','${unpaidUser}'
    )`,
  );
  assert.equal(claim.claimed, false);
  assert.equal(claim.claim_state, 'subscription_required');
  assert.match(claim.message, /active CareFlow subscription/i);

  const [unpaid] = await asService(
    `select public.careflow_service_has_paid_access('${unpaidOrg}','${unpaidUser}') as allowed`,
  );
  const [paid] = await asService(
    `select public.careflow_service_has_paid_access('${liveOrg}','${liveUser}') as allowed`,
  );
  assert.equal(unpaid.allowed, false);
  assert.equal(paid.allowed, true);
});

test('the migration keeps entitlement helpers and mutation RPCs least-privilege', () => {
  assert.match(migration, /create policy "Paid hospitals can update cases"[\s\S]*as restrictive/i);
  assert.match(migration, /provider_variant_id = 'pri_01m2gcpjxz4wqjft7z10zcz3zq'/i);
  assert.match(migration, /p_actor_id = '5ebb6f53-f8b6-464d-af65-c19fa3a28e85'::uuid/i);
  assert.match(migration, /revoke all on function careflow_private\.organization_has_paid_access\(uuid, uuid\)[\s\S]*authenticated/i);
  assert.doesNotMatch(migration, /grant execute on function careflow_private\.organization_has_paid_access\(uuid, uuid\)[\s\S]*to authenticated/i);
  assert.match(migration, /grant execute on function public\.careflow_has_paid_access\(uuid\) to authenticated/i);
  assert.match(migration, /revoke all on function public\.careflow_service_has_paid_access\(uuid, uuid\)[\s\S]*authenticated/i);
  assert.match(migration, /grant execute on function public\.careflow_service_has_paid_access\(uuid, uuid\)[\s\S]*to service_role/i);
  assert.match(migration, /'subscription_required'::text/);
});
